print("Anfang des Programms")
name = input("Bitte deinen Namen eingeben: ")
print("Mein Name ist " + name)
age = input("Bitte dein aktuelles Alter eingeben: ")
print("Mein Alter ist " + age)
print("Ende des Programms")